[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Service-Worker-Allowed = "/" 